### ISSUE TITLE
Request: Support filtering on pod name

### ISSUE THREAD

**Issue by atombender** [dtan4/k8stail#16]
I've been using [kubetail](https://github.com/johanhaleby/kubetail) lately because it allows me to just do:

```
$ kubetail postgres
Will tail 1 logs...
postgresql-master-1744499466-r9znc
[...]
```

However, kubetail is just a shell script and has limited ability to do things like watch for new pods, and doesn't support multiple containers per pod. I'd love to have this filtering ability in k8stail.

It goes without saying, I think, that it should watch for _new_ pods that match the filters (including labels) and also stop tailing old pods that go away.

**Comment by dtan4** [comment]
I don't indend to implement Pod filter, because Kubernetes API does not provide the feature.
If you want to filter output by pod name, please use grep instead. Output always includes its pod name.

```bash
$ k8stail | grep --line-buffered postgres
```

Of course, pull requests are always welcome :octocat:
